#!/usr/bin/python
import sys
import swsssdk

argc = len(sys.argv)
if argc == 2 and sys.argv[1] == '-h':
    print "Example 1: sonic-db-cli CONFIG_DB keys *"
    print "Example 2: sonic-db-cli APPL_DB HGETALL VLAN_TABLE:Vlan10"
    print "Example 3: sonic-db-cli APPL_DB HGET VLAN_TABLE:Vlan10 mtu"
elif argc < 3:
    msg = "'Usage: sonic-db-cli <db_name> <cmd> [arg [arg ...]]'. See 'sonic-db-cli -h' for detail examples."
    print >> sys.stderr, msg
else:
    dbname = sys.argv[1]
    dbconn = swsssdk.SonicV2Connector(use_unix_socket_path=False)
    try:
        dbconn.connect(dbname)
    except RuntimeError:
        msg = "Invalid database name input : '{}'".format(sys.argv[1])
        print >> sys.stderr, msg
    else:
        client = dbconn.get_redis_client(dbname)
        print client.execute_command(" ".join(sys.argv[2:]))
